#!/usr/bin/env python3

import html
import sys
import time

import lxml.html
import requests

def user(username):
    url = "https://open.kattis.com/users/" + username
    r = requests.get(url)
    doc = lxml.html.fromstring(r.text)
    rt = doc.find(".//div[@class='rank clearfix']")
    rank, score = [eval(i.text.strip()) for i in rt.findall(".//td") if i.text]

    return rank, score

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: %s username" % sys.argv[0])
        exit(1)

    username = sys.argv[1]

    try:
        r, s = user(username)
    except:
        print("Not found", file=sys.stderr)
        exit(1)

    print("%.6f\t%s\t%d\t%.2f" % (time.time(), username, r, s))
